Repository potato-club/national-petition-backend, pull requests merged in 2021-09, with the labels that each got.

#3 국민청원 크롤러 서버 API 연동
  build.gradle
  src/main/java/com/example/nationalpetition/config/FeignClientConfig.java
  src/main/java/com/example/nationalpetition/config/FeignErrorDecoder.java
  src/main/java/com/example/nationalpetition/external/petition/PetitionClient.java
  src/main/java/com/example/nationalpetition/external/petition/dto/response/PetitionResponse.java
  src/main/resources/application.yml
Labels: enhancement

#7 feat: 국민 청원 인기 TOP5 API Client
  build.gradle
  src/main/java/com/example/nationalpetition/config/WebClientConfig.java
  src/main/java/com/example/nationalpetition/external/petition/PetitionRankClient.java
  src/main/java/com/example/nationalpetition/external/petition/PetitionRankClientImpl.java
  src/main/java/com/example/nationalpetition/external/petition/dto/response/PetitionRankResponse.java
Labels: enhancement

#16 [BAC-16] 실시간 청원 인기 TOP5 조회 API
  .gitignore
  src/docs/asciidoc/api.adoc
  src/main/java/com/example/nationalpetition/controller/rank/PetitionRankController.java
  src/test/java/com/example/nationalpetition/controller/rank/PetitionRankControllerTest.java
Labels: enhancement

#20 [BAC-7] feat: comment 생성(댓글+대댓글)
  src/main/java/com/example/nationalpetition/NationalPetitionApplication.java
  src/main/java/com/example/nationalpetition/controller/comment/CommentController.java
  src/main/java/com/example/nationalpetition/domain/comment/Comment.java
  src/main/java/com/example/nationalpetition/domain/comment/CommentRepository.java
  src/main/java/com/example/nationalpetition/domain/comment/CommentRepositoryCustom.java
  src/main/java/com/example/nationalpetition/domain/comment/CommentRepositoryCustomImpl.java
  src/main/java/com/example/nationalpetition/dto/CommentCreateDto.java
  src/main/java/com/example/nationalpetition/dto/comment/CommentCreateDto.java
  src/main/java/com/example/nationalpetition/dto/comment/request/CommentUpdateDto.java
  src/main/java/com/example/nationalpetition/service/comment/CommentService.java
  src/test/java/com/example/nationalpetition/domain/CommentTest.java
  src/test/java/com/example/nationalpetition/service/comment/CommentServiceTest.java
  src/test/java/com/example/nationalpetition/serviceTest/CommentServiceTest.java
Labels: enhancement

#30 [BAC-2] K8s 개발 서버 및 CI/CD 구축
  .github/workflows/deploying.yml
  .github/workflows/testing.yml
  Dockerfile
  VERSION
  build.gradle
  src/main/java/com/example/nationalpetition/controller/LocalController.java
  src/main/resources/application.yml
Labels: enhancement

#31 Feat/like
  http/board/board.http
  src/docs/asciidoc/api-board.adoc
  src/docs/asciidoc/api.adoc
  src/main/java/com/example/nationalpetition/controller/board/BoardController.java
  src/main/java/com/example/nationalpetition/domain/board/Board.java
  src/main/java/com/example/nationalpetition/domain/board/BoardLike.java
  src/main/java/com/example/nationalpetition/domain/board/BoardState.java
  src/main/java/com/example/nationalpetition/domain/board/repository/BoardLikeRepository.java
  src/main/java/com/example/nationalpetition/domain/board/repository/BoardLikeRepositoryCustom.java
  src/main/java/com/example/nationalpetition/domain/board/repository/BoardLikeRepositoryCustomImpl.java
  src/main/java/com/example/nationalpetition/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/nationalpetition/domain/member/entity/Member.java
  src/main/java/com/example/nationalpetition/dto/board/request/BoardLikeRequest.java
  src/main/java/com/example/nationalpetition/dto/board/request/DeleteBoardLikeRequest.java
  src/main/java/com/example/nationalpetition/service/board/BoardService.java
  src/main/java/com/example/nationalpetition/utils/error/ErrorCode.java
  src/main/java/com/example/nationalpetition/utils/error/controllerAdvice/ExceptionControllerAdvice.java
  src/main/java/com/example/nationalpetition/utils/error/errorCode/ErrorCode.java
  src/main/java/com/example/nationalpetition/utils/error/exception/ConflictException.java
  src/main/java/com/example/nationalpetition/utils/error/exception/ValidationException.java
  src/test/java/com/example/nationalpetition/controller/board/BoardControllerTest.java
  src/test/java/com/example/nationalpetition/service/board/BoardServiceTest.java
  src/test/java/com/example/nationalpetition/testObject/BoardCreator.java
  src/test/java/com/example/nationalpetition/testObject/BoardLikeCreator.java
Labels: help wanted

#36 [BAC-18] : DTO 변환 계층 수정 및 테스트코드 작성
  src/main/java/com/example/nationalpetition/controller/member/MemberController.java
  src/main/java/com/example/nationalpetition/dto/member/request/NickNameRequest.java
  src/main/java/com/example/nationalpetition/service/member/MemberService.java
  src/main/java/com/example/nationalpetition/service/member/MemberServiceImpl.java
  src/test/java/com/example/nationalpetition/service/member/MemberServiceTest.java
Labels: help wanted

#37 [BAC-29] : 회원 닉네임 등록 API 기능 및 테스트코드 개발
  src/main/java/com/example/nationalpetition/config/MessageConfig.java
  src/main/java/com/example/nationalpetition/controller/member/MemberController.java
  src/main/java/com/example/nationalpetition/domain/member/repository/MemberRepository.java
  src/main/java/com/example/nationalpetition/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/example/nationalpetition/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/example/nationalpetition/dto/member/request/NickNameRequest.java
  src/main/java/com/example/nationalpetition/service/member/MemberService.java
  src/main/java/com/example/nationalpetition/service/member/MemberServiceImpl.java
  src/main/java/com/example/nationalpetition/service/member/MemberServiceUtils.java
  src/main/java/com/example/nationalpetition/utils/error/ErrorCode.java
  src/main/java/com/example/nationalpetition/utils/error/controllerAdvice/ExceptionControllerAdvice.java
  src/main/java/com/example/nationalpetition/utils/error/exception/AlreadyExistException.java
  src/main/java/com/example/nationalpetition/utils/error/exception/DuplicateException.java
  src/main/resources/messages.properties
  src/main/resources/validation.properties
  src/test/java/com/example/nationalpetition/controller/member/MemberControllerTest.java
  src/test/java/com/example/nationalpetition/service/member/MemberServiceTest.java
Labels: help wanted

#39 [BAC-22] : 회원 탈퇴 API 기능 및 테스트코드 개발
  src/main/java/com/example/nationalpetition/controller/member/MemberController.java
  src/main/java/com/example/nationalpetition/domain/member/entity/DeleteMember.java
  src/main/java/com/example/nationalpetition/domain/member/entity/Member.java
  src/main/java/com/example/nationalpetition/domain/member/repository/DeleteMemberRepository.java
  src/main/java/com/example/nationalpetition/dto/member/DeleteMessageConst.java
  src/main/java/com/example/nationalpetition/service/member/MemberService.java
  src/main/java/com/example/nationalpetition/service/member/MemberServiceImpl.java
  src/test/java/com/example/nationalpetition/controller/member/MemberControllerTest.java
  src/test/java/com/example/nationalpetition/service/member/MemberServiceTest.java
Labels: enhancement, help wanted

#42 배너...
  src/main/resources/banner.txt
Labels: help wanted
